project:
  output-dir: "C:/Users/nickb/Projects/1. Uncommon Sense/Website/docs"
  type: website
  render: 
    - index.qmd
    - journal.qmd
    - archive.qmd
    - data-report-ATPW127.qmd
    - md/Rights
    - md/Issues
    - md/Solutions
format:
  html:
    theme: bootstrap
    # theme: none
    css: /assets/css/default-styles.css
    # include-in-header: "_includes/custom-header-dev.html" #Pet project - creating header from scratch
    include-after-body: "_includes/generated-navbar.html" #Functional example navbar
website:
  title: "Uncommon Sense"
  # favicon: /images/test-image.png
  announcement: 
    icon: cone-striped
    dismissable: true
    content: "This website is under active development. Report an issue [here](https://github.com/niboXR/UncommonSenseProject/issues)."
    position: below-navbar
    type: warning
  navbar:
    collapse-below: lg
    toggle-position: right
    search: false
    left:
      - text: ""
    right:
      - text: "More"
        menu: 
          - archive.qmd
          - journal.qmd
search: false
# metadata-files: 
#   - _navbar.yml